name: test-dispatcher-filters-ubuntu
# run the workflow manually
on: [workflow_dispatch]
jobs:
  test_dispatcher_filters:
    container:
      image: redhat/ubi8:latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yum -y --nogpgcheck install httpd
      - run: cp httpd-renderer.conf /etc/httpd/conf/httpd-renderer.conf
      - run: mkdir -p /etc/httpd/conf.dispatcher.d/filters
      - run: mkdir -p /etc/httpd/modules/dispatcher
      - run: mkdir -p /var/www/renderer
      - run: cp dispatcher/mod_dispatcher.so /etc/httpd/modules/dispatcher/mod_dispatcher.so
      - run: cp httpd-dispatcher.conf /etc/httpd/conf.d/httpd-dispatcher.conf
      - run: cp dispatcher.any /etc/httpd/conf.dispatcher.d/dispatcher.any
      #- run: cat /etc/apache2/httpd.conf
      #- run: cat /etc/httpd/conf.d/default.conf
      - run: cp 02-dispatcher.conf /etc/httpd/conf.d/02-dispatcher.conf
      - run: cp index.html /var/www/renderer/index.html
      - run: /usr/sbin/httpd -D FOREGROUND -f /etc/httpd/conf/httpd-renderer.conf &
      - run: sleep 2
      - run: /usr/sbin/httpd -D FOREGROUND
      - run: curl -I localhost
